### ISSUE TITLE
Add elegant iteration over EnTT views

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#52]
```cpp
for(auto const& [things, from, the, view] : reg.materialized_view<MachineRocket, ACompTransform>())
{

}
```
"[...] we could probably make an iterator type fairly easily that would accomplish the task."

_Originally posted by @jonesmz in https://github.com/TheOpenSpaceProgram/osp-magnum/pull/49#discussion_r559088259_

**Comment by skypjack** [comment]
Hi, I've been following this project since someone mentioned it on the discord server of EnTT. I found it pretty interesting.
So, today I came across this issue by chance and probably this is what you're looking for?
```
for(auto [entity, tcomp, ucomp]: reg.view<T, U>().each()) {
    // ...
}
```
By default EnTT offers iterators that only return entities. This is to make them at least forward iterators and therefore suitable for uses with standard parallel algorithms.
However, there is also an `.each()` function (without lambdas) that returns an iterable object that offers _extended iterators_ out of the box. Because of how the standard is defined, these iterators are in the input category, but still.
I hope it works for you. 👍

**Comment by z-adams** [comment]
That's very slick, I'll have to try this. Thanks! And thanks for your interest in the project; we're currently in the process of merging a bunch of parallel branches and will soon be on our way to some more externally visible features. Keep your eyes peeled in the next few weeks/months.
